version: "3.3"

services:
  express:
    container_name: express
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./:/home
      - /home/node_modules/
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/1-dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"

volumes:
  mysql:
